Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/daler/.local/lib/python2.7/site-packages/flask/__main__.py", line 15, in <module>
    main(as_module=True)
  File "/home/daler/.local/lib/python2.7/site-packages/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/home/daler/.local/lib/python2.7/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/home/daler/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/daler/.local/lib/python2.7/site-packages/click/core.py", line 1061, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/home/daler/.local/lib/python2.7/site-packages/click/core.py", line 1100, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/home/daler/.local/lib/python2.7/site-packages/flask/cli.py", line 351, in get_command
    rv = info.load_app().cli.get_command(ctx, name)
  File "/home/daler/.local/lib/python2.7/site-packages/flask/cli.py", line 237, in load_app
    rv = locate_app(self.app_import_path)
  File "/home/daler/.local/lib/python2.7/site-packages/flask/cli.py", line 90, in locate_app
    __import__(module)
  File "/home/daler/1520_web_dev/assignmets/a3/cater.py", line 13, in <module>
    from models import db, User, Event, Event_Assignee
  File "/home/daler/1520_web_dev/assignmets/a3/models.py", line 41, in <module>
    class Event_Assignee(db.Model):
  File "/home/daler/.local/lib/python2.7/site-packages/flask_sqlalchemy/model.py", line 67, in __init__
    super(NameMetaMixin, cls).__init__(name, bases, d)
  File "/home/daler/.local/lib/python2.7/site-packages/flask_sqlalchemy/model.py", line 121, in __init__
    super(BindMetaMixin, cls).__init__(name, bases, d)
  File "/home/daler/.local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/api.py", line 64, in __init__
    _as_declarative(cls, classname, cls.__dict__)
  File "/home/daler/.local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 88, in _as_declarative
    _MapperConfig.setup_mapping(cls, classname, dict_)
  File "/home/daler/.local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 103, in setup_mapping
    cfg_cls(cls_, classname, dict_)
  File "/home/daler/.local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 131, in __init__
    self._setup_table()
  File "/home/daler/.local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 395, in _setup_table
    **table_kw)
  File "/home/daler/.local/lib/python2.7/site-packages/flask_sqlalchemy/model.py", line 99, in __table_cls__
    return sa.Table(*args, **kwargs)
  File "/home/daler/.local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 439, in __new__
    metadata._remove_table(name, schema)
  File "/home/daler/.local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/daler/.local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 434, in __new__
    table._init(name, metadata, *args, **kw)
  File "/home/daler/.local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 518, in _init
    self._init_items(*args)
  File "/home/daler/.local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 79, in _init_items
    item._set_parent_with_dispatch(self)
  File "/home/daler/.local/lib/python2.7/site-packages/sqlalchemy/sql/base.py", line 432, in _set_parent_with_dispatch
    self.dispatch.after_parent_attach(self, parent)
  File "/home/daler/.local/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 256, in __call__
    fn(*args, **kw)
  File "/home/daler/.local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 1907, in _set_table
    **self._unvalidated_dialect_kw
  File "/home/daler/.local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 2866, in __init__
    info=info, **dialect_kw)
  File "/home/daler/.local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 2496, in __init__
    self._validate_dialect_kwargs(dialect_kw)
  File "/home/daler/.local/lib/python2.7/site-packages/sqlalchemy/sql/base.py", line 282, in _validate_dialect_kwargs
    "named <dialectname>_<argument>, got '%s'" % k)
TypeError: Additional arguments should be named <dialectname>_<argument>, got 'nullable'
